clc;
clear all;
close all;
t = -5:1:5;
y1 = [zeros(1,5),ones(1,1),zeros(1,5)];
subplot(3,3,1);
stem(t,y1);
xlabel('time index');
ylabel('amplitude');
title('Unit Implulse');
y2 = [zeros(1,5),ones(1,6)];
subplot(3,3,2);
stem(t,y2);
xlabel('time index');
ylabel('amplitude');
title('Unit Step');
t3 = 0:1:5;
y3 = t3;
subplot(3,3,3);
plot(t3,y3);
hold on;
stem(t3,y3);
xlabel('time index');
ylabel('amplitude');
title('Unit Ramp');
legend("Continuous","Discrete");
t4 = 0:0.01:1;
f4 = 4;
subplot(3,3,4);
y4 = sin(2*pi*f4*t4);
plot(t4,y4);
hold on;
stem(t4,y4);
xlabel('time index');
ylabel('amplitude');
title('Sine Wave');
legend("Continuous","Discrete");
subplot(3,3,5);
y5 = cos(2*pi*f4*t4);
plot(t4,y5);
hold on;
stem(t4,y5);
xlabel('time index');
ylabel('amplitude');
title('Cosine Wave');
legend("Continuous","Discrete");
t6 = 0:0.0001:1;
f6 = 10;
subplot(3,3,6);
plot(t6,square(2*pi*f6*t6));
xlabel('time index');
ylabel('amplitude');
title('Square Wave - Bipolar');
subplot(3,3,7);
plot(t6,sqrt(square(2*pi*f6*t6)));
xlabel('time index');
ylabel('amplitude');
title('Square Wave - Unipolar');
subplot(3,3,8);
t8 = 0:0.01:1;
f8 = 10;
y8 = sawtooth(2*pi*f8*t8,0.5);
plot(t8,y8);
hold on;
stem(t8,y8);
xlabel('time index');
ylabel('amplitude');
title('Triangular Wave');
legend("Continuous","Discrete");
subplot(3,3,9);
t9 = 0:0.1:5;
y9 = exp(t9);
plot(t9,y9);
hold on;
stem(t9,y9);
xlabel('time index');
ylabel('amplitude');
title('Exponential Signal');
legend("Continuous","Discrete");


