clc;
clear all;
close all;
xn = input('Enter input x(n): ');
hn = input('Enter input h(n): ');
x_len = length(xn);
h_len = length(hn);
y_len = x_len+h_len-1;
newx = [xn zeros(1,y_len-x_len)];
newh = [hn zeros(1,y_len-h_len)];
x = fft(newx);
h = fft(newh);
hx = x.*h;
y = ifft(hx);
disp('Linear convolution using Circular convolution: ');
disp(round(y));
